### ISSUE TITLE
Musicbot failed on startup when i hosted

### ISSUE THREAD

**Issue by StonebanksYT** [solaluset/DandelionMusic#106]
i had the following error when i started the bot
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/http.py", line 418, in static_login
    data = await self.request(Route("GET", "/users/@me"))
  File "/home/container/.local/lib/python3.9/site-packages/discord/http.py", line 371, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/musicbot/__main__.py", line 65, in <module>
    bot.run(config.BOT_TOKEN, reconnect=True)
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 765, in run
    return future.result()
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 744, in runner
    await self.start(*args, **kwargs)
  File "/home/container/musicbot/bot.py", line 52, in start
    return await super().start(*args, **kwargs)
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 707, in start
    await self.login(token)
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 561, in login
    data = await self.http.static_login(token.strip())
  File "/home/container/.local/lib/python3.9/site-packages/discord/http.py", line 422, in static_login
    raise LoginFailure("Improper token has been passed.") from exc
discord.errors.LoginFailure: Improper token has been passed.
Set the correct token in config.json
/usr/local/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 5 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by solaluset** [comment]
Looks like the token you've entered is not valid
