### ISSUE TITLE
Please help me with this error I dont know what it means

### ISSUE THREAD

**Issue by StonebanksYT** [solaluset/DandelionMusic#123]
Traceback (most recent call last):
  File "/home/container/run.py", line 106, in <module>
    main()
  File "/home/container/run.py", line 20, in main
    runpy.run_module("musicbot", run_name="__main__")
  File "/usr/local/lib/python3.9/runpy.py", line 228, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/container/musicbot/__main__.py", line 65, in <module>
    bot.run(config.BOT_TOKEN, reconnect=True)
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 766, in run
    return future.result()
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 745, in runner
    await self.start(*args, **kwargs)
  File "/home/container/musicbot/bot.py", line 52, in start
    return await super().start(*args, **kwargs)
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 708, in start
    await self.login(token)
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 562, in login
    data = await self.http.static_login(token.strip())
  File "/home/container/.local/lib/python3.9/site-packages/discord/http.py", line 420, in static_login
    data = await self.request(Route("GET", "/users/@me"))
  File "/home/container/.local/lib/python3.9/site-packages/discord/http.py", line 326, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward.
/usr/local/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 5 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by solaluset** [comment]
It means that you have somehow reached the rate limit. Usually this should disappear after some time.
