### ISSUE TITLE
Spotify / Youtube nothing is working

### ISSUE THREAD

**Issue by Soham-Das-afk** [solaluset/DandelionMusic#215]
Spotify error:
(windows cmd part attached, not working in docker/linux)
Playing https://open.spotify.com/playlist/37i9dQZF1E4nr8oSbqldFh?pi=a-Auya-nxdTK2r
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "aiohttp\connector.py", line 1098, in _wrap_create_connection
  File "asyncio\base_events.py", line 1113, in create_connection
  File "asyncio\base_events.py", line 1146, in _create_connection_transport
  File "asyncio\sslproto.py", line 578, in _on_handshake_complete
  File "asyncio\sslproto.py", line 560, in _do_handshake
  File "ssl.py", line 979, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "concurrent\futures\process.py", line 261, in _process_worker
  File "musicbot\loader.py", line 143, in _load_song
  File "asyncio\base_events.py", line 654, in run_until_complete
  File "musicbot\linkutils.py", line 121, in fetch_spotify
  File "musicbot\linkutils.py", line 105, in get_soup
  File "aiohttp\client.py", line 1359, in __aenter__
  File "aiohttp\client.py", line 663, in _request
  File "aiohttp\connector.py", line 563, in connect
  File "aiohttp\connector.py", line 1032, in _create_connection
  File "aiohttp\connector.py", line 1366, in _create_direct_connection
  File "aiohttp\connector.py", line 1335, in _create_direct_connection
  File "aiohttp\connector.py", line 1100, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host open.spotify.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\ext\commands\core.py", line 180, in wrapped
  File "musicbot\commands\music.py", line 87, in _play
  File "musicbot\commands\music.py", line 96, in _play_song
  File "musicbot\audiocontroller.py", line 382, in process_song
  File "musicbot\audiocontroller.py", line 319, in play_song
  File "musicbot\loader.py", line 221, in preload
  File "musicbot\loader.py", line 125, in load_song
  File "musicbot\loader.py", line 235, in _run_sync
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host open.spotify.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\ext\bridge\bot.py", line 144, in invoke
  File "discord\ext\commands\core.py", line 959, in invoke
  File "discord\ext\commands\core.py", line 189, in wrapped
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientConnectorCertificateError: Cannot connect to host open.spotify.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

Youtube:
(Windows working fine, docker/linux not working even after updating config)
Error: Unable to fetch song info. If you're trying to access age restricted content, check the documentation/wiki.

FYI: There are some updated in (if that helps)
1. https://github.com/aio-libs/aiohttp 
2. https://github.com/yt-dlp/yt-dlp

i already updated the requirements.txt in docker but its still not working

**Comment by solaluset** [comment]
Try adding `pip-system-certs` to your requirements

**Comment by Soham-Das-afk** [comment]
It finally worded
